### ISSUE TITLE
créer un dossier globale

### ISSUE THREAD

**Issue by hajar-co** [saidworks/foracademy#1]
guys c'est mieux ikon hdchi wst un dossier

**Comment by hajar-co** [comment]
mercii said

**Comment by hajar-co** [comment]
said wch dak dossier . idea kharj 3la for academy

**Comment by saidworks** [comment]
Essaie de voir c'est tu peux te connecter au db, c'est résolu

**Comment by hajar-co** [comment]
d'accord merci
